In [2]:
import numpy as np 
import torch

Autograd is an automatic differentiator

In [3]:
a = torch.tensor([5.],requires_grad=True)
b = torch.tensor([6.],requires_grad=True)

In [9]:
y = a ** 3 - b ** 2

In [10]:
y

tensor([89.], grad_fn=<SubBackward0>)

In [11]:
# dy/da = 3 a ^2 = 75
# dy/db = - 2 b  = -12

In [13]:
print(a.grad,b.grad)

None None


In [14]:
y.backward()
# Now we have a value of a.grad and b.grad

In [15]:
print(a.grad,b.grad)

tensor([75.]) tensor([-12.])


In [16]:
W = torch.randn(10,1,requires_grad=True)
b = torch.randn(1,requires_grad=True)


In [18]:
x1 = torch.rand(1,10)
x1

tensor([[0.2747, 0.3872, 0.8952, 0.1488, 0.0195, 0.8412, 0.2245, 0.7468, 0.0655,
         0.4189]])

In [19]:
weighted_sum = torch.matmul(x1,W) + b
weighted_sum

tensor([[1.3613]], grad_fn=<AddBackward0>)

In [20]:
loss = 1 - weighted_sum
loss

tensor([[-0.3613]], grad_fn=<RsubBackward1>)

In [21]:
loss.backward()

In [22]:
W.grad

tensor([[-0.2747],
        [-0.3872],
        [-0.8952],
        [-0.1488],
        [-0.0195],
        [-0.8412],
        [-0.2245],
        [-0.7468],
        [-0.0655],
        [-0.4189]])

In [24]:
learning_rate = 0.001

In [26]:
with torch.no_grad():
    W = W - learning_rate * W.grad.data
print(W)

tensor([[-0.8381],
        [ 2.2706],
        [ 0.3414],
        [-2.4012],
        [-0.5018],
        [ 1.1668],
        [-0.0086],
        [-1.4136],
        [-0.1616],
        [-0.0245]])
