In [7]:
# Describing Einsum - for learning purpose
import torch
# from numpy import einsum
# from tensorflow import einsum
from torch import einsum

In [ ]:
#einsum(equation,operands)

In [14]:
print("\tTranspose\n")
t = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print("Actual tensor\n",t)
print("\nAfter transpose")
einsum('ij->ji',[t])

	Transpose

Actual tensor
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

After transpose


tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [25]:
print("\tSum")
t = torch.tensor([[1,2],[3,4],[-2,-7]],dtype=torch.float32)
print(t)
t_sum = einsum('ij->',[t])
print("\nThe sum is : ",t_sum)


	Sum
tensor([[ 1.,  2.],
        [ 3.,  4.],
        [-2., -7.]])

The sum is :  tensor(1.)


In [29]:
print("Dot Product")
t1 = torch.tensor([12,14,17],dtype=torch.float32)
t2 = torch.arange(7,10,dtype=torch.float32)
print(t1, t2)
print("Dot product = ",einsum('i,i->',[t1,t2]))

Dot Product
tensor([12., 14., 17.]) tensor([7., 8., 9.])
Dot product =  tensor(349.)


In [34]:
print("Matrix Multiplication")
t1 = torch.arange(1,10).reshape(3,3)
t2 = torch.arange(7,13).reshape(3,2)
print(t1,"\n",t2)

print("t1 * t2 =",einsum('ik,kj->ij',[t1,t2]))

Matrix Multiplication
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) 
 tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])
t1 * t2 = tensor([[ 58,  64],
        [139, 154],
        [220, 244]])
