In [2]:
import csv
import torch
import numpy as np
import opendatasets as od
import os

In [3]:
od.download('https://www.kaggle.com/datasets/piyushagni5/white-wine-quality')

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username:Your Kaggle Key:Downloading white-wine-quality.zip to .\white-wine-quality


100%|██████████| 73.1k/73.1k [00:00<00:00, 398kB/s]

In [3]:
csv_path = 'G:/py-py-py-pytorch/Initial/white-wine-quality/winequality-white.csv'
np_arr = np.loadtxt(csv_path,dtype=np.float32,delimiter=';',skiprows=1)


In [4]:
np_arr

array([[ 7.  ,  0.27,  0.36, ...,  0.45,  8.8 ,  6.  ],
       [ 6.3 ,  0.3 ,  0.34, ...,  0.49,  9.5 ,  6.  ],
       [ 8.1 ,  0.28,  0.4 , ...,  0.44, 10.1 ,  6.  ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  0.46,  9.4 ,  6.  ],
       [ 5.5 ,  0.29,  0.3 , ...,  0.38, 12.8 ,  7.  ],
       [ 6.  ,  0.21,  0.38, ...,  0.32, 11.8 ,  6.  ]], dtype=float32)

In [5]:
wine_t = torch.from_numpy(np_arr)

In [6]:
wine_t

tensor([[ 7.0000,  0.2700,  0.3600,  ...,  0.4500,  8.8000,  6.0000],
        [ 6.3000,  0.3000,  0.3400,  ...,  0.4900,  9.5000,  6.0000],
        [ 8.1000,  0.2800,  0.4000,  ...,  0.4400, 10.1000,  6.0000],
        ...,
        [ 6.5000,  0.2400,  0.1900,  ...,  0.4600,  9.4000,  6.0000],
        [ 5.5000,  0.2900,  0.3000,  ...,  0.3800, 12.8000,  7.0000],
        [ 6.0000,  0.2100,  0.3800,  ...,  0.3200, 11.8000,  6.0000]])

In [7]:
openr = csv.reader(open(csv_path),delimiter=',')
col_list = next(openr)
col_list

['fixed acidity;"volatile acidity";"citric acid";"residual sugar";"chlorides";"free sulfur dioxide";"total sulfur dioxide";"density";"pH";"sulphates";"alcohol";"quality"']

In [23]:
data = wine_t[:,:-1]
labels = wine_t[:,-1]
labels = labels.type(dtype=torch.int64)

In [27]:
data.shape, labels.shape

(torch.Size([4898, 11]), torch.Size([4898]))

In [28]:
labels

tensor([6, 6, 6,  ..., 6, 7, 6])

In [30]:
# scatter_()   - One Hot Encoding
target_onehot = torch.zeros(labels.shape[0],10)

target_onehot.scatter_(1,labels.unsqueeze(1),1.0)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])