In [36]:
import numpy as np
import torch

In [2]:
a = torch.ones(3,2)
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [3]:
a[2,0] = 2
a

tensor([[1., 1.],
        [1., 1.],
        [2., 1.]])

In [4]:
print(float(a[2,1]))

1.0


In [5]:
a = [[1,2,3],[3,4,5],[5,6,7]]
a_tensor = torch.tensor(a)
a_tensor

tensor([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]])

In [6]:
l = list(range(6))
l
l[:5]

[0, 1, 2, 3, 4]

In [7]:
img_t = torch.randn(3,5,5)
weights = torch.tensor([0.2124,0.7152,0.0722])


In [8]:
img_t

tensor([[[ 0.0846,  0.0408,  0.1411,  0.7226, -1.1527],
         [ 0.4903,  0.8845,  2.4389,  0.8120,  0.1765],
         [ 1.6802, -0.1064,  0.3137,  1.1564,  0.2854],
         [-0.5047, -0.3802,  1.7438,  2.5764,  0.6908],
         [-2.6140,  0.1855,  1.4227, -1.5982,  0.3578]],

        [[-1.6954, -0.3463,  0.2720, -0.1873, -0.4363],
         [ 0.2193,  0.2677, -2.9773,  1.0920, -0.4360],
         [-1.5100, -0.7536,  0.4873, -0.6700,  1.3414],
         [ 1.3560,  0.4988, -1.6593, -0.7722, -0.2740],
         [-0.9892,  0.1886,  0.7788, -1.0460, -0.0913]],

        [[ 0.4982, -0.0831, -0.1574,  0.7439, -0.3985],
         [-0.3425,  1.0660, -1.1089,  0.9347, -0.8341],
         [ 1.3825, -2.0424, -0.6613,  1.6561, -1.1278],
         [-0.4330,  2.0548,  0.0805,  1.0143,  1.3515],
         [-0.2911, -0.2355, -0.5469,  0.6385, -0.1130]]])

In [9]:
batch_t = torch.randn(2,3,5,5)

In [10]:
img_gray = img_t.mean(-3) # lazy unweighted mean
batch_gray = batch_t.mean(-3)
print(img_gray.shape,batch_gray.shape)


torch.Size([5, 5]) torch.Size([2, 5, 5])


In [11]:
img_gray

tensor([[-0.3709, -0.1295,  0.0852,  0.4264, -0.6625],
        [ 0.1224,  0.7394, -0.5491,  0.9462, -0.3645],
        [ 0.5176, -0.9675,  0.0466,  0.7142,  0.1663],
        [ 0.1394,  0.7245,  0.0550,  0.9395,  0.5894],
        [-1.2981,  0.0462,  0.5515, -0.6686,  0.0512]])

In [12]:
unsq_weights = weights.unsqueeze(-1).unsqueeze_(-1) 

print("The shape of unsqueezed weights : {0}".format(unsq_weights.shape))
print("\nThe shape of img_tensor : {0}".format(img_t.shape))
print("\nThe shape of batch_tensor : {0}".format(batch_t.shape))

img_weights = (img_t * unsq_weights)
batch_weights = (batch_t * unsq_weights)

print("\nAfter multiplying, the shape of img_weights is {}\nthe shape of batch_weights is {}".format(img_weights.shape,batch_weights.shape))


The shape of unsqueezed weights : torch.Size([3, 1, 1])

The shape of img_tensor : torch.Size([3, 5, 5])

The shape of batch_tensor : torch.Size([2, 3, 5, 5])

After multiplying, the shape of img_weights is torch.Size([3, 5, 5])
the shape of batch_weights is torch.Size([2, 3, 5, 5])


In [13]:
print("Named Weights\n")
weights_n = torch.tensor([0.2126,0.7152,0.0722],names=['channels'])
print(weights_n)

Named Weights

tensor([0.2126, 0.7152, 0.0722], names=('channels',))


C:\Users\thepr\AppData\Local\Temp\ipykernel_30368\1687844413.py:2: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1463.)
  weights_n = torch.tensor([0.2126,0.7152,0.0722],names=['channels'])


In [14]:
# refine_names
img_t_named = img_t.refine_names(...,'channels','rows','columns')
batch_t_named = batch_t.refine_names(...,'channels','rows','columns')

print(img_t_named.names,batch_t_named.names)



('channels', 'rows', 'columns') (None, 'channels', 'rows', 'columns')


In [15]:
weights_n_aligned = weights_n.align_as(img_t_named)
print(weights_n_aligned)
print(weights_n_aligned.shape)
print(weights_n_aligned.names)

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]], names=('channels', 'rows', 'columns'))
torch.Size([3, 1, 1])
('channels', 'rows', 'columns')


In [16]:
t_1 = torch.arange(1,10,dtype=torch.float32).reshape(3,3)
print(t_1)
t_1 = t_1.refine_names(...,'a','b')
t_1 = t_1.align_as(t_1)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [17]:
sum_t = t_1.sum('a')
print(sum_t)

tensor([12., 15., 18.], names=('b',))


In [18]:
print('API Func.\n')
a = torch.ones(3,2)
a_ = torch.transpose(a,0,1)
print("{}\n".format(a))
print("{}\n".format(a_))

API Func.

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

tensor([[1., 1., 1.],
        [1., 1., 1.]])



In [19]:
print("Storage_Views\n")
tensor_1 = torch.tensor([[2,0,1],[3,1,7],[9,4,5]])
print('Tensor 1         :  \n{}\n'.format(tensor_1))
print('Tensor_st_view   :  \n{}\n'.format(tensor_1.storage()))

Storage_Views

Tensor 1         :  
tensor([[2, 0, 1],
        [3, 1, 7],
        [9, 4, 5]])

Tensor_st_view   :  
 2
 0
 1
 3
 1
 7
 9
 4
 5
[torch.LongStorage of size 9]



In [60]:
tensor_1[1].storage_offset()

3

In [21]:
my_tensor = torch.rand(3,4)
my_tensor

tensor([[0.5283, 0.8314, 0.6599, 0.5146],
        [0.7844, 0.1614, 0.8483, 0.0976],
        [0.1004, 0.5309, 0.1928, 0.2388]])

In [25]:
print(my_tensor.device)
my_tensor = my_tensor.to("cuda")
print(my_tensor.device)



cpu
cuda:0


In [27]:
my_tensor[:,1:]

tensor([[0.8314, 0.6599, 0.5146],
        [0.1614, 0.8483, 0.0976],
        [0.5309, 0.1928, 0.2388]], device='cuda:0')

In [29]:
# Elementwise
my_tensor.mul(my_tensor)
my_tensor * my_tensor

tensor([[0.2791, 0.6912, 0.4355, 0.2648],
        [0.6153, 0.0261, 0.7196, 0.0095],
        [0.0101, 0.2818, 0.0372, 0.0570]], device='cuda:0')

In [32]:
# Matrix Multiplication
my_tensor.matmul(my_tensor.T)
torch.matmul(my_tensor,my_tensor.T)
my_tensor @ my_tensor.T

tensor([[1.6706, 1.1582, 0.7445],
        [1.1582, 1.3699, 0.3512],
        [0.7445, 0.3512, 0.3860]], device='cuda:0')

In [37]:
arr = [[1,2,3],[4,5,6],[7,8,9]]
np_arr = np.asarray(arr)
tensor_1 = torch.from_numpy(np_arr)
tensor_1

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32)

In [39]:
print(tensor_1.sum(axis=0))
print(tensor_1.sum(axis=1))

tensor([12, 15, 18])
tensor([ 6, 15, 24])


In [41]:
torch.cat([my_tensor,my_tensor],axis=1)

tensor([[0.5283, 0.8314, 0.6599, 0.5146, 0.5283, 0.8314, 0.6599, 0.5146],
        [0.7844, 0.1614, 0.8483, 0.0976, 0.7844, 0.1614, 0.8483, 0.0976],
        [0.1004, 0.5309, 0.1928, 0.2388, 0.1004, 0.5309, 0.1928, 0.2388]],
       device='cuda:0')

In [43]:
torch.nn.functional.softmax(my_tensor,dim=1)

tensor([[0.2232, 0.3022, 0.2545, 0.2201],
        [0.3220, 0.1727, 0.3433, 0.1620],
        [0.2091, 0.3215, 0.2293, 0.2401]], device='cuda:0')

In [46]:
my_tensor.shape

torch.Size([3, 4])

In [48]:
torch.rand(10,3,128,128).shape

torch.Size([10, 3, 128, 128])

In [49]:
#Clippling operation 
my_tensor.clip(0.2,0.8)

tensor([[0.5283, 0.8000, 0.6599, 0.5146],
        [0.7844, 0.2000, 0.8000, 0.2000],
        [0.2000, 0.5309, 0.2000, 0.2388]], device='cuda:0')

In [50]:
my_tensor.cpu().detach().numpy()

array([[0.52827615, 0.83141387, 0.6599014 , 0.5146011 ],
       [0.78438544, 0.16142142, 0.84830976, 0.0975855 ],
       [0.10035336, 0.5308653 , 0.19281822, 0.23875731]], dtype=float32)