In [1]:
import torch

In [5]:
a = torch.ones(3,2)
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [6]:
a[2,0] = 2
a

tensor([[1., 1.],
        [1., 1.],
        [2., 1.]])

In [11]:
print(float(a[2,1]))

1.0


In [12]:
a = [[1,2,3],[3,4,5],[5,6,7]]
a_tensor = torch.tensor(a)
a_tensor

tensor([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]])

In [13]:
l = list(range(6))
l
l[:5]

[0, 1, 2, 3, 4]

In [14]:
img_t = torch.randn(3,5,5)
weights = torch.tensor([0.2124,0.7152,0.0722])


In [21]:
img_t

tensor([[[ 1.1485, -1.6306,  1.4567, -0.3608,  0.3380],
         [-0.6960,  0.1877,  0.7792, -0.3296, -0.5024],
         [ 0.0082, -0.2893,  0.9109,  2.1747,  0.6809],
         [-0.5131,  0.4713, -0.2134,  0.1797, -2.5766],
         [ 1.3368,  0.1103, -0.9111,  0.5832,  0.1367]],

        [[ 0.4149, -0.5292, -0.4215, -0.1083, -0.7333],
         [ 0.2278,  0.5313, -0.0295,  0.5976,  0.6232],
         [ 0.4160,  1.1668, -1.0755,  1.1747,  0.5657],
         [ 0.4254, -0.6774,  0.6938,  0.4343,  0.6005],
         [-0.3470, -0.1010, -1.1311,  0.1503, -1.3737]],

        [[-1.0400,  1.3302, -0.6822,  1.3560, -1.9215],
         [-1.1262,  0.4544, -0.4941, -0.0885, -0.7574],
         [ 2.5431,  0.2233,  1.6895, -1.5261,  2.5241],
         [ 0.8608,  0.1876,  0.2665, -0.1353, -1.0072],
         [-0.6682, -0.0323,  0.1902,  0.9402,  2.2153]]])

In [15]:
batch_t = torch.randn(2,3,5,5)

In [16]:
img_gray = img_t.mean(-3) # lazy unweighted mean
batch_gray = batch_t.mean(-3)
print(img_gray.shape,batch_gray.shape)


torch.Size([5, 5]) torch.Size([2, 5, 5])


In [20]:
img_gray

tensor([[ 0.1745, -0.2765,  0.1177,  0.2956, -0.7723],
        [-0.5315,  0.3912,  0.0852,  0.0598, -0.2122],
        [ 0.9891,  0.3669,  0.5083,  0.6078,  1.2569],
        [ 0.2577, -0.0062,  0.2490,  0.1596, -0.9944],
        [ 0.1072, -0.0077, -0.6173,  0.5579,  0.3261]])

In [24]:
unsq_weights = weights.unsqueeze(-1).unsqueeze_(-1) 

print("The shape of unsqueezed weights : {0}".format(unsq_weights.shape))
print("\nThe shape of img_tensor : {0}".format(img_t.shape))
print("\nThe shape of batch_tensor : {0}".format(batch_t.shape))

img_weights = (img_t * unsq_weights)
batch_weights = (batch_t * unsq_weights)

print("\nAfter multiplying, the shape of img_weights is {}\nthe shape of batch_weights is {}".format(img_weights.shape,batch_weights.shape))


The shape of unsqueezed weights : torch.Size([3, 1, 1])

The shape of img_tensor : torch.Size([3, 5, 5])

The shape of batch_tensor : torch.Size([2, 3, 5, 5])

After multiplying, the shape of img_weights is torch.Size([3, 5, 5])
the shape of batch_weights is torch.Size([2, 3, 5, 5])


In [27]:
print("Named Weights\n")
weights_n = torch.tensor([0.2126,0.7152,0.0722],names=['channels'])
print(weights_n)

Named Weights

tensor([0.2126, 0.7152, 0.0722], names=('channels',))


In [28]:
# refine_names
img_t_named = img_t.refine_names(...,'channels','rows','columns')
batch_t_named = batch_t.refine_names(...,'channels','rows','columns')

print(img_t_named.names,batch_t_named.names)



('channels', 'rows', 'columns') (None, 'channels', 'rows', 'columns')


In [32]:
weights_n_aligned = weights_n.align_as(img_t_named)
print(weights_n_aligned)
print(weights_n_aligned.shape)
print(weights_n_aligned.names)

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]], names=('channels', 'rows', 'columns'))
torch.Size([3, 1, 1])
('channels', 'rows', 'columns')


In [44]:
t_1 = torch.arange(1,10,dtype=torch.float32).reshape(3,3)
print(t_1)
t_1 = t_1.refine_names(...,'a','b')
t_1 = t_1.align_as(t_1)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [46]:
sum_t = t_1.sum('a')
print(sum_t)

tensor([12., 15., 18.], names=('b',))
