In [1]:
#Workflow
import torch
from torch import nn #basic building block of neural network (graphs)
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

2.0.1+cu117


In [6]:
print(torch.cuda.is_available())
print(torch.version.cuda)

True
11.7


In [8]:
a = torch.tensor([1,2,3])
a = a.cuda()
a

tensor([1, 2, 3], device='cuda:0')

### Ranks, Axes and Shapes

In [9]:
t = torch.tensor([
  [1,1,1],
  [2,2,2],
  [3,3,3],
  [4,4,4]
 ],dtype=torch.float32) 

t

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.]])

In [12]:
print(t.shape)

torch.Size([4, 3])


In [14]:
# Each element in axis 1 is an array
# note: can't exceed 3 because the len of axis 1 is 4
print(t[0])
print(t[1])
print(t[2])
print(t[3])

tensor([1., 1., 1.])
tensor([2., 2., 2.])
tensor([3., 3., 3.])
tensor([4., 4., 4.])


In [16]:
#Each element in axis 2 is an element
# note: can't exceed 2 because the len of axis 2 is 3
print(t[0][0])
print(t[0][1])
print(t[0][2])

print(t[1][0])
print(t[1][1])
print(t[1][2])

print(t[2][0])
print(t[2][1])
print(t[2][2])

print(t[3][0])
print(t[3][1])
print(t[3][2])

tensor(1.)
tensor(1.)
tensor(1.)
tensor(2.)
tensor(2.)
tensor(2.)
tensor(3.)
tensor(3.)
tensor(3.)
tensor(4.)
tensor(4.)
tensor(4.)


In [17]:
print("Rank of the tensor = {}".format(len(t.shape)))

Rank of the tensor = 2


In [21]:
print(t.reshape(1,12))
print(t.reshape(1,12).shape)

tensor([[1., 1., 1., 2., 2., 2., 3., 3., 3., 4., 4., 4.]])
torch.Size([1, 12])
