In [32]:
import torch
import numpy as np

In [13]:
t = torch.Tensor()
print(type(t))

print(t.dtype)

print(t.device)

print(t.layout) # how tensors are laid out in memory. set at default


<class 'torch.Tensor'>
torch.float32
cpu
torch.strided


In [12]:
device = torch.device('cuda:0')
print(device)

cuda:0


Creating Tensor

In [20]:
arr = np.array([1,2,3])
print(type(arr))

t1 = torch.Tensor(arr) #class constructor
print(t1, t1.dtype) #by default Float

<class 'numpy.ndarray'>
tensor([1., 2., 3.]) torch.float32


In [17]:
t2 = torch.tensor(arr)
print(t2)

tensor([1, 2, 3], dtype=torch.int32)


In [21]:
t3 = torch.as_tensor(arr)
print(t3)

tensor([1, 2, 3], dtype=torch.int32)


In [22]:
t4 = torch.from_numpy(arr)
print(t4)

tensor([1, 2, 3], dtype=torch.int32)


creation without data:

In [24]:
t5 = torch.eye(3)
print(t5)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [25]:
t6 = torch.zeros(2,2)
print(t6)

tensor([[0., 0.],
        [0., 0.]])


In [30]:
t7 = torch.ones(3,3)
print(t7)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [31]:
t_rand = torch.rand(2,2)
print(t_rand)

tensor([[0.0587, 0.8211],
        [0.0837, 0.1573]])


### Memory Sharing & Copying

In [33]:
data = np.array([1,2,3])
data

array([1, 2, 3])

In [34]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [35]:
data[0] = 0
data[1] = 0
data[2] = 0

In [36]:
print(t1)
print(t2)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)


In [37]:
print(t3)
print(t4)

tensor([0, 0, 0], dtype=torch.int32)
tensor([0, 0, 0], dtype=torch.int32)
