## Tensor Operations


- Reshaping
- Element-wise
- Reduction
- Access

In [1]:
import torch
import numpy as np

In [2]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
])

In [8]:
print("The shape is ",t.shape)
print("Rank is ",len(t.shape))
print("The are {} elements".format(t.numel()))

The shape is  torch.Size([3, 4])
Rank is  2
The are 12 elements


In [10]:
t.reshape(6,2)


tensor([[1, 1],
        [1, 1],
        [2, 2],
        [2, 2],
        [3, 3],
        [3, 3]])

In [12]:
# squeeze & unsqueeze
t_reshaped = t.reshape(1,12).squeeze()
t_reshaped.shape

torch.Size([1, 12])

In [15]:
def flatten(t):
    t = t.reshape(1,-1)
    t = t.squeeze()
    return t

In [17]:
flatten(t).shape

torch.Size([12])

In [19]:
t.reshape(12).shape

torch.Size([12])

### Flatten in CNN - working

In [26]:
t1 = torch.ones(4,4,dtype=torch.int32)
t2 = t1*2
t3 = t1*3

print(t1)
print(t2)
print(t3)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)
tensor([[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]], dtype=torch.int32)
tensor([[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]], dtype=torch.int32)


In [28]:
t = torch.stack((t1,t2,t3))
t.shape

torch.Size([3, 4, 4])

In [29]:
#add a color channel axis 
cnn_input = t.reshape(3,1,4,4)
cnn_input

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]], dtype=torch.int32)

In [30]:
cnn_input[0] # first image

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]], dtype=torch.int32)

In [32]:
# we only flatten image tensor 
cnn_input.reshape(1,-1)[0] # here entire is flattened

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       dtype=torch.int32)

In [33]:
cnn_input.flatten(start_dim=1).shape

torch.Size([3, 16])