## Tensor Operations


- Reshaping
- Element-wise
- Reduction
- Access

In [1]:
import torch
import numpy as np

In [2]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
])

In [8]:
print("The shape is ",t.shape)
print("Rank is ",len(t.shape))
print("The are {} elements".format(t.numel()))

The shape is  torch.Size([3, 4])
Rank is  2
The are 12 elements


In [10]:
t.reshape(6,2)


tensor([[1, 1],
        [1, 1],
        [2, 2],
        [2, 2],
        [3, 3],
        [3, 3]])

In [12]:
# squeeze & unsqueeze
t_reshaped = t.reshape(1,12).squeeze()
t_reshaped.shape

torch.Size([1, 12])

In [15]:
def flatten(t):
    t = t.reshape(1,-1)
    t = t.squeeze()
    return t

In [17]:
flatten(t).shape

torch.Size([12])

In [19]:
t.reshape(12).shape

torch.Size([12])

### Flatten in CNN - working

In [26]:
t1 = torch.ones(4,4,dtype=torch.int32)
t2 = t1*2
t3 = t1*3

print(t1)
print(t2)
print(t3)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)
tensor([[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]], dtype=torch.int32)
tensor([[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]], dtype=torch.int32)


In [28]:
t = torch.stack((t1,t2,t3))
t.shape

torch.Size([3, 4, 4])

In [29]:
#add a color channel axis 
cnn_input = t.reshape(3,1,4,4)
cnn_input

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]], dtype=torch.int32)

In [30]:
cnn_input[0] # first image

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]], dtype=torch.int32)

In [32]:
# we only flatten image tensor 
cnn_input.reshape(1,-1)[0] # here entire is flattened

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       dtype=torch.int32)

In [33]:
cnn_input.flatten(start_dim=1).shape

torch.Size([3, 16])

## Element-wise

In [34]:
t1 = torch.tensor([
    [1,2],
    [3,4]
])
t2 = torch.tensor([
    [9,8],
    [7,6]
])


In [35]:
t1 + t2

tensor([[10, 10],
        [10, 10]])

In [37]:
# Here the 2 is broadcasted to the shape of t1 before elementwise operation (addition)
t1 + 2

tensor([[3, 4],
        [5, 6]])

In [38]:
np.broadcast_to(2,t1.shape)

array([[2, 2],
       [2, 2]])

In [46]:
t1 + torch.tensor(np.broadcast_to(2,t1.shape))

tensor([[3, 4],
        [5, 6]])

In [50]:
# another eg.
ta = torch.tensor([
    [1,2],
    [3,4]
],dtype=torch.int32)

tb = torch.tensor([1,2],dtype=torch.int32)

In [48]:
print(ta.shape
, tb.shape)

torch.Size([2, 2]) torch.Size([1, 2])


In [49]:
ta + tb

tensor([[2, 4],
        [4, 6]], dtype=torch.int32)

In [52]:
t1 = torch.tensor([[1,2,3]])
t2 = torch.tensor([[1],
      [2],
      [3]])


In [53]:
print(t1.shape,t2.shape)

torch.Size([1, 3]) torch.Size([3, 1])


Another example

In [54]:
t1 + t2

tensor([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])

In [55]:
np.broadcast_to(t1,(3,3))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]], dtype=int64)

In [56]:
np.broadcast_to(t2,(3,3))

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]], dtype=int64)

In [60]:
t1 = torch.tensor([
    [1,2,3],
    [4,5,6]
],dtype=torch.float32)

In [62]:
t1.ge(2).type(torch.uint8)

tensor([[0, 1, 1],
        [1, 1, 1]], dtype=torch.uint8)