## Reduction

Helps to do operations within a tensor

In [1]:
import torch
import numpy as np

In [2]:
t = torch.tensor([
    [2,0,3],
    [0,7,9],
    [1,4,6]
],dtype=torch.float32)

In [4]:
print(t.sum())
print(t.numel())
print(t.mean())
print(t.std())
print(t.prod())

tensor(32.)
9
tensor(3.5556)
tensor(3.2059)
tensor(0.)


Does reduction always reduce to a single element? No


In [9]:
print(t,"\n")
print(t.sum(dim=0),
t.sum(dim=1))

print("Basically, the dim 0 is the first axis that are arrays so")
print(t[0],"\n",t[1],"\n",t[2],"\n")
print("We add these element-wise to obtain the sum of dim 0.")

tensor([[2., 0., 3.],
        [0., 7., 9.],
        [1., 4., 6.]]) 

tensor([ 3., 11., 18.]) tensor([ 5., 16., 11.])
Basically, the dim 0 is the first axis that are arrays so
tensor([2., 0., 3.]) 
 tensor([0., 7., 9.]) 
 tensor([1., 4., 6.]) 

We add these element-wise to obtain the sum of dim 0.


### argmax

In [11]:
t1 = torch.tensor([
    [1,0,3],
    [9,7,1],
    [0,0,5],
],dtype=torch.float32)

In [12]:
t1.max()

tensor(9.)

In [23]:
print(t1.argmax())
print(t1.argmax(dim=0))
print(t1.argmax(dim=1))

tensor(3)
tensor([1, 1, 2])
tensor([2, 0, 2])


In [37]:
pred = torch.tensor([[0.08],[0.78],[0.21],[0.19],[0.56],[0.71]])

pred.argmax(dim=1)

tensor([1])