In [1]:
import torch
import torchvision

### For Scalar

In [5]:
x = torch.arange(4.0,requires_grad=True)
f = torch.dot(x,x)
print(x,"\n",f)

tensor([0., 1., 2., 3.], requires_grad=True) 
 tensor(14., grad_fn=<DotBackward0>)


In [7]:
f.backward()
print(x.grad)

tensor([0., 2., 4., 6.])


In [8]:
print(x.grad == 2*x)

tensor([True, True, True, True])


In [9]:
#python accumulates gradients by default, so we need to clear it up whenever required

f = x.sum()
print(f)

tensor(6., grad_fn=<SumBackward0>)


In [11]:
f.backward()
print(x.grad) # we see the values are added 

tensor([1., 3., 5., 7.])


In [12]:
x.grad.zero_()
f.backward()
print(x.grad)

tensor([1., 1., 1., 1.])


### For Non-Scalars

In [15]:
x = torch.tensor([0,1,2],dtype=torch.float32,requires_grad=True)
y = x*x

#since y has multiple outputs, we pass the v vector
y.backward(gradient=torch.tensor([1.0,1.0,1.0]))
print(x.grad)

tensor([0., 2., 4.])


### Detaching Computation